### PR TITLE
Update Role and Material to better detect duplicates

### LINKED ISSUE #190: [PE-D][Tester A] Unable to detect duplicated roles/materials
When accidentally adding duplicated roles/materials in event creation, the app won't detect and report the error.  

It's great that the app lists out the roles and materials by first letter order. However, it is possible that users enter duplicated roles/materials when inputting tremendous, complicated event details. The roles and materials should be modified to have the same duplication detection as skills in volunteers and also case-insensitive.  

**_Unable to detect duplicated "cleaner" and "pairs of gloves":_**

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: A1WAYSD/ped#10

### PR DESCRIPTION
**Pull request by brein62**
- Updated role and material formats in `ecreate` within UG (@tiongMax to update in `eedit`) to make the format more clear (#144), as well as include the duplicate detection (#190)
- Updated UG to indicate duplicated behaviour for roles and materials will show as duplicates

### CODE REVIEW

**Comment by brein62** [comment]
i think this should be ok as a functionality bug since the validation in this case is relaxed, and not added. the feature flaw part about case-sensitivity is not added and reflected in the UG instead. what do y'all think

**Comment by ruo-x** [comment]
i think its a feature flaw eh sadly... because our feature still works perfectly without it

**Review by jordankanghm — APPROVED** [review]
lgtm brother

**Review by zacwong2151 — APPROVED** [review]

**Comment by ruo-x** [comment]
wait so r we gonna push this pr if not can j delete?

**Comment by brein62** [comment]
> > wait so r we gonna push this pr if not can j close?
> 
> idk I let @brein62 close it but he seems to be afking for a bit

hello bro was not free but now bro is free

**Pull request merged**
