### PR TITLE
Fix eshow bug

### PR DESCRIPTION
**Pull request by ruo-x**
**1. changed UI to only show a single event at all times** (to solve issue #166)
**2. event show window closes whenever the main window close** - fixed this as previously, our app would encounter an error (functionality bug) through the following steps: 1. I open eshow window 2. i exit the main app (note the event show window will still be opened) 3. i run the app again

### CODE REVIEW

**Review by zacwong2151 — APPROVED** [review]

**Comment by brein62** [comment]
ok on second thought do you think this is a feature flaw? since the eshow feature works perfectly just that extras show up. hopefully there is sth in the UG to back up the fact that there should only be 1 event shown in the `eshow` feature

**Comment by ruo-x** [comment]
i dont think this is a feature flaw because my ug did mention they can get to read more about an **individual** event though

**Review by zacwong2151 — APPROVED** [review]
looking good

**Review by jordankanghm — APPROVED** [review]
bad job but lgtm tho

**Pull request merged**
